services:
  - type: web
    name: appwoyofal
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromDatabase:
          name: postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  - type: postgres
    name: postgres
    plan: free
    ipAllowList: []